name: Procedure Name
comment: XYZ
version: 111
files:
  - path: "global_constants.csv"
    type: global_constants_csv
  - path: "./benzene.xyz"
    type: xyz
    name: benz
    timestep: "init"
  - path: "./benzene.xyz"
    type: xyz
    name: gurke  
    timestep: "transition state"
  - path: "./benzene.xyz"
    type: xyz
    name: abcd  
substitutions:
  - name: S1
    entries:
    - file: benz
      atom_index: 5
    - file: gurke
      atom_index: 4
    - file: abcd
      atom_index: 1
measurements:
  distance:
    - name: O-H-bond
      a: 6
      b: 7
    - name: Subs-bond
      a: S1
      b: 10
  angle:
    - name: H-O-H
      a: 3
      b: 6
      c: 7
    - name: H-O-N
      a: 8
      b: 9
      c: 10
  dihedral:
    - name: torsion1
      a: 2
      b: 3
      c: 6
      d: 7
calc:
  - name: energy
    expr: "(6.0 * Eh2o_kcalmol)+(HF * )"
  - name: böp
    expr: "np.sqrt(pi * H-O-H)"
  - name: böps
    expr: "pi * H-O-H"
  - name: böpn
    expr: "böp * böp"
output:
  - file:
    - path: ./out.csv
      type: csv
    - path: ./out_tuples.csv
      type: csv_tuples   
  - graph:
      - type: scatter_plot
        y:
          - 'H-O-H'
          - 'H-O-N'
        x: 'torsion1'
        x_label: "torsion1"
        y_label:
          - "H-O-H"
          - "H-O-N"
        file: ./series_plot.png
        file_format: png
        dpi: 300
  