name: Procedure Name
comment: XYZ
version: 111
files:
  - path: "benzene*.xyz"
    type: xyz
    name: benz-
    glob: True
  - path: bx.xyz
    type: xyz
    name: bxyz
substitutions:
  - name: S1
    entries:
    - file: benz-*
      atom_index: 5
      glob: True
    - file: bxyz
      atom_index: 8 
measurements:
  distance:
    - name: O-H-bond
      a: 6
      b: 7
    - name: Subs-bond
      a: S1
      b: 10
  angle:
    - name: H-O-H
      a: 3
      b: 6
      c: 7
    - name: H-O-N
      a: 11
      b: 9
      c: 10
  dihedral:
    - name: torsion1
      a: 2
      b: 3
      c: 6
      d: 7
output:
  - file:
    - path: ./out.csv
      type: csv
  - graph:
    - type: scatter_plot
      x: Subs-bond
      y: H-O-N 
      file: ./SB-HON.tiff
      