name: Procedure Name
comment: XYZ
version: 111
files:
  - path: "./benzene.xyz"
    type: xyz
    name: benz
  - path: "./benzene.xyz"
    type: xyz
    name: benz2  
  - path: "./benzene.xyz"
    type: xyz
    name: benz3  
substitutions:
  - name: S1
    entries:
    - file: benz
      atom_index: 5
    - file: benz2
      atom_index: 4
    - file: benz3
      atom_index: 1
measurements:
  distance:
    - name: O-H-bond
      a: 6
      b: 7
    - name: Subs-bond
      a: S1
      b: 10
  angle:
    - name: H-O-H
      a: 3
      b: 6
      c: 7
    - name: H-O-N
      a: 8
      b: 9
      c: 10
  dihedral:
    - name: torsion1
      a: 2
      b: 3
      c: 6
      d: 7
output:
  - file:
    - path: ./out.csv
      type: csv
  - graph:
    - type: scatter_plot
      x: distance-Subs-bond
      y: angle-H-O-N 
      file: ./SB-HON.tiff
      